### ISSUE TITLE
ui design

### ISSUE THREAD

**Issue by prestonp** [open-austin/permit-prereq-check#1]
https://github.com/open-austin/permit-server/issues/55

**Comment by brainnews** [comment]
V5 wires attached
[permitting_v5.zip](https://github.com/open-austin/permit-preqreq-check/files/471074/permitting_v5.zip)

**Comment by twentysixmoons** [comment]
@brainnews we might want to reconsider these icons
<img width="370" alt="screen shot 2016-09-13 at 9 55 21 pm" src="https://cloud.githubusercontent.com/assets/10767430/18498548/dde54eee-79fc-11e6-82d4-2b865312ff33.png">
- If you're not in a floodplain then that is good. You don't have to do anything. 
- If you are in an airport overlay zone then that's okay because you don't have to do anything before submission. You may have to do something later. 
- IIf you are in historic district then you have to complete another application before moving forward. 

What do you think about simplifying it to 2 icons? 
- 1 icon to mean no action currently required (Maybe the green check)
- 1 icon to let you know there is a rode block (Maybe the yield sign)

So we'd get rid of the "x" mark? 

Thoughts on that?

**Comment by twentysixmoons** [comment]
Also! Do submit what you have for the updated flow/color when you get a chance. Sketch and pdf/png would be good so Preston and Kevin can see.

**Comment by brainnews** [comment]
@VictoriaODell Totally agree re: simplifying to two icons. good call.

@prestonp @kmclaugh – Here are the updated files.

**PDF:** [permitting_v5.pdf](https://github.com/open-austin/permit-prereq-check/files/474637/permitting_v5.pdf)

**Sketch:** [permitting_v5.zip](https://github.com/open-austin/permit-prereq-check/files/474642/permitting_v5.zip)

Let me know if you have any comments about the new design elements (map placement, about modal, etc).

**Comment by prestonp** [comment]
@brainnews The design looks great! Do you have the icons available in svg or png?

**Comment by brainnews** [comment]
@prestonp – thanks! sorry for the delay.
[graphics.zip](https://github.com/open-austin/permit-prereq-check/files/489665/graphics.zip)

**Comment by prestonp** [comment]
@brainnews no worries!! tyvm!!

**Comment by prestonp** [comment]
Got most of the design covered. Now to add form interactivity and figure out source data for address checks
